# Generated by Django 4.1.5 on 2023-01-21 11:58

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_en', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_fa', models.BooleanField(default=False, verbose_name='is active')),
                ('name', models.CharField(max_length=350, verbose_name='name')),
                ('name_en', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('name_fa', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='The phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='message')),
                ('message_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='message')),
                ('message_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact-Us',
                'verbose_name_plural': 'Contact-Us',
            },
        ),
    ]
