# Generated by Django 4.1.5 on 2023-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=1, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_active_en',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=1, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_active_fa',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=1, null=True, verbose_name='is active ?'),
        ),
    ]
