# Generated by Django 4.1.5 on 2023-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_contactus_created_at_jalali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='required_services',
            field=models.CharField(choices=[('DET', 'Dedicatedtranslation'), ('SIT', 'Simpletranslation'), ('ECT', 'Economictranslation'), ('SPT', 'Specialtranslation')], default='SIT', max_length=3, verbose_name='required_services'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='required_services_en',
            field=models.CharField(choices=[('DET', 'Dedicatedtranslation'), ('SIT', 'Simpletranslation'), ('ECT', 'Economictranslation'), ('SPT', 'Specialtranslation')], default='SIT', max_length=3, null=True, verbose_name='required_services'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='required_services_fa',
            field=models.CharField(choices=[('DET', 'Dedicatedtranslation'), ('SIT', 'Simpletranslation'), ('ECT', 'Economictranslation'), ('SPT', 'Specialtranslation')], default='SIT', max_length=3, null=True, verbose_name='required_services'),
        ),
    ]
