# Generated by Django 4.1.5 on 2023-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_contactus_required_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='required_services',
            field=models.CharField(choices=[('DedicatedTranslation', 'Dedicatedtranslation'), ('SimpleTranslation', 'Simpletranslation'), ('EconomicTranslation', 'Economictranslation'), ('SpecialTranslation', 'Specialtranslation')], default='SimpleTranslation', max_length=20, verbose_name='required_services'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='required_services_en',
            field=models.CharField(choices=[('DedicatedTranslation', 'Dedicatedtranslation'), ('SimpleTranslation', 'Simpletranslation'), ('EconomicTranslation', 'Economictranslation'), ('SpecialTranslation', 'Specialtranslation')], default='SimpleTranslation', max_length=20, null=True, verbose_name='required_services'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='required_services_fa',
            field=models.CharField(choices=[('DedicatedTranslation', 'Dedicatedtranslation'), ('SimpleTranslation', 'Simpletranslation'), ('EconomicTranslation', 'Economictranslation'), ('SpecialTranslation', 'Specialtranslation')], default='SimpleTranslation', max_length=20, null=True, verbose_name='required_services'),
        ),
    ]
