# Generated by Django 4.1.5 on 2023-04-06 11:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_created_at_jalali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title'),
        ),
    ]
