# Generated by Django 4.1.5 on 2023-03-25 17:42

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Subscription')),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_en', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_fa', models.BooleanField(default=False, verbose_name='is active')),
                ('name', models.CharField(max_length=350, verbose_name='name')),
                ('name_en', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('name_fa', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('company', models.CharField(max_length=20, verbose_name='company')),
                ('company_en', models.CharField(max_length=20, null=True, verbose_name='company')),
                ('company_fa', models.CharField(max_length=20, null=True, verbose_name='company')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='marketing/user_comment/user_comment/avatar/2023/3', verbose_name='avatar')),
                ('avatar_alt', models.CharField(blank=True, max_length=350, verbose_name='avatar alt')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='rate')),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comments',
            },
        ),
    ]
