# Generated by Django 4.1.5 on 2023-02-25 07:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('name', models.CharField(max_length=350, verbose_name='name')),
                ('company', models.CharField(max_length=20, verbose_name='company')),
                ('avatar', models.ImageField(upload_to='marketing/user_comment/user_comment/avatar/2023/2', verbose_name='avatar')),
                ('avatar_alt', models.CharField(blank=True, max_length=350, verbose_name='avatar alt')),
                ('rate', models.PositiveSmallIntegerField(default=0, max_length=1, verbose_name='rate')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comments',
            },
        ),
    ]
