# Generated by Django 4.1.5 on 2023-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rate'),
        ),
    ]
