# Generated by Django 4.1.5 on 2023-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_usercomment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/user_comment/user_comment/avatar/2023/4', verbose_name='avatar'),
        ),
    ]
