# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_usercomment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='emailsubscription',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='updated_at_jalali',
        ),
    ]
