# Generated by Django 4.1.5 on 2023-02-25 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_usercomment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='company_en',
            field=models.CharField(max_length=20, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='company_fa',
            field=models.CharField(max_length=20, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='content_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='is_active_en',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='is_active_fa',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='name_en',
            field=models.CharField(max_length=350, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='name_fa',
            field=models.CharField(max_length=350, null=True, verbose_name='name'),
        ),
    ]
