# Generated by Django 4.1.5 on 2023-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_remove_emailsubscription_created_at_jalali_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/user_comment/user_comment/avatar/2023/5', verbose_name='avatar'),
        ),
    ]
