# Generated by Django 4.1.5 on 2023-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_usercomment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/user_comment/user_comment/avatar/2023/3', verbose_name='avatar'),
        ),
    ]
