# Generated by Django 4.1.5 on 2023-03-25 17:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_en', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_fa', models.BooleanField(default=False, verbose_name='is active')),
                ('meta_title', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title')),
                ('meta_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='meta description')),
                ('status', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, verbose_name='status')),
                ('status_en', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status')),
                ('status_fa', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('title_en', models.CharField(max_length=350, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=350, null=True, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/3', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('short_description', models.CharField(max_length=50, null=True, verbose_name='Short Discription')),
                ('short_description_en', models.CharField(max_length=50, null=True, verbose_name='Short Discription')),
                ('short_description_fa', models.CharField(max_length=50, null=True, verbose_name='Short Discription')),
                ('study_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='study time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_en', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_fa', models.BooleanField(default=False, verbose_name='is active')),
                ('status', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, verbose_name='status')),
                ('name', models.CharField(max_length=350, verbose_name='name')),
                ('name_en', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('name_fa', models.CharField(max_length=350, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='message')),
                ('message_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='message')),
                ('message_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='message')),
                ('dislike', models.ManyToManyField(related_name='dislike_comments', to=settings.AUTH_USER_MODEL, verbose_name='Dislikes')),
                ('likes', models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='comment')),
                ('post_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='comment')),
                ('post_fa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='comment')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.postcomment', verbose_name='reply')),
                ('reply_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.postcomment', verbose_name='reply')),
                ('reply_fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.postcomment', verbose_name='reply')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_en', models.BooleanField(default=False, verbose_name='is active')),
                ('is_active_fa', models.BooleanField(default=False, verbose_name='is active')),
                ('meta_title', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title')),
                ('meta_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='meta description')),
                ('status', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, verbose_name='status')),
                ('status_en', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status')),
                ('status_fa', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('title_en', models.CharField(max_length=350, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=350, null=True, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='taxonomy/thumbnails/2023/3', verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='thumbnail alt')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.postcategory', verbose_name='parent category')),
                ('parent_category_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.postcategory', verbose_name='parent category')),
                ('parent_category_fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.postcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.postcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.postcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_fa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.postcategory', verbose_name='category'),
        ),
    ]
