# Generated by Django 4.1.5 on 2023-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_is_active_alter_post_is_active_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
    ]
