# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_thumbnail_alter_postcategory_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='updated_at_jalali',
        ),
    ]
