# Generated by Django 4.1.5 on 2023-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_created_at_jalali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_fa',
        ),
    ]
