# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at_jalali',
        ),
    ]
