# Generated by Django 4.1.5 on 2023-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/2023/5', verbose_name='thumbnail'),
        ),
    ]
