# Base Serializer
from .serializer_base_post import BasePostSerializer
from .serializer_base_comment import BaseCommentSerializer
from .serializer_base_category import BaseCategorySerializer

# Post Serializer
from .serializer_list_post import ListPostSerializer
from .serializer_detail_post import DetailPostSerializer
from .serializer_create_update_post import CreateUpdatePostSerializer

# Post Category Serializer
from .serializer_list_category import ListCategorySerializer
from .serializer_detail_category import DetailCategorySerializer
from .serializer_create_update_category import CreateUpdateCategorySerializer

# Post Comment serializer
from .serializer_list_comment import ListCommentSerializer
from .serializer_detail_comment import DetailCommentSerializer
from .serializer_create_update_comment import CreateUpdateCommentSerializer
