# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='projectgallery',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='projectgallery',
            name='updated_at_jalali',
        ),
    ]
