# Generated by Django 4.1.5 on 2023-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
    ]
