# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='updated_at_jalali',
        ),
    ]
