from .serializer_base_social_media import SocialMediaBaseSerializer
from .serializer_base_team_member import TeamMemberBaseSerializer

from .serializer_customers import CustomersSerializer

from .serializer_landing_sections import LandingSectionsSerializer


from .serializer_team_member_create_update import TeamMembersCreateUpdateSerializer
from .serializer_team_member_detail import TeamMembersDetailSerializer
from .serialzieer_team_member_list import TeamMembersListSerializer

from .serialzier_social_medai_detail import SocialMediaDetailSerializer
from .serialzier_social_medai_list import SocialMediaListSerializer
from .serialzier_social_media_create_updaet import SocialMediaCreateUpdateSerializer