# Generated by Django 4.1.5 on 2023-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/logo/2023/3', verbose_name='Customer Logo'),
        ),
    ]
