# Generated by Django 4.1.5 on 2023-04-01 09:33

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0003_alter_landingsections_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at_jalali', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?')),
                ('status', models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, verbose_name='status')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.AlterField(
            model_name='customers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/logo/2023/4', verbose_name='Customer Logo'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_background',
            field=models.ImageField(upload_to='landing_sections/cover_background/2023/4', verbose_name='Cover Background'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_main',
            field=models.ImageField(upload_to='landing_sections/cover_main/2023/4', verbose_name='Cover Main'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_video',
            field=models.ImageField(upload_to='landing_sections/cover_video/2023/4', verbose_name='Cover Video'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('position', models.CharField(max_length=200, verbose_name='position')),
                ('avatar', models.ImageField(upload_to='dastres/about/avatar/2023/4', verbose_name='avatar')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='dastres.socialmedia', verbose_name='about')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
