# Generated by Django 4.1.5 on 2023-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0004_socialmedia_alter_customers_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AddField(
            model_name='about',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='about',
            name='position_en',
            field=models.CharField(max_length=200, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='about',
            name='position_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='is_active_en',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='is_active_fa',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, null=True, verbose_name='is active ?'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='status_en',
            field=models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='status_fa',
            field=models.CharField(choices=[('PU', 'Publish'), ('IN', 'Inriview'), ('PE', 'Pending')], default='PE', max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
