# Generated by Django 4.1.5 on 2023-04-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0005_about_is_active_en_about_is_active_fa_about_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='dastres.about', verbose_name='social media'),
            preserve_default=False,
        ),
    ]
