# Generated by Django 4.1.5 on 2023-04-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0007_alter_about_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='TeamMembers',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='about',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='team_members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='dastres.teammembers', verbose_name='team_members'),
            preserve_default=False,
        ),
    ]
