# Generated by Django 4.1.5 on 2023-04-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0008_rename_about_teammembers_remove_socialmedia_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='team_members',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='social_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dastres.socialmedia', verbose_name='social_media'),
            preserve_default=False,
        ),
    ]
