# Generated by Django 4.1.5 on 2023-04-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0009_remove_socialmedia_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='team_members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='dastres.teammembers', verbose_name='social media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Github', 'Github'), ('Instagram', 'Instagram'), ('Website', 'Website')], max_length=10, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title_en',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Github', 'Github'), ('Instagram', 'Instagram'), ('Website', 'Website')], max_length=10, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title_fa',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Github', 'Github'), ('Instagram', 'Instagram'), ('Website', 'Website')], max_length=10, null=True, verbose_name='title'),
        ),
    ]
