# Generated by Django 4.1.5 on 2023-04-01 11:56

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0010_remove_teammembers_social_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=0, verbose_name='is active ?')),
                ('meta_title', models.CharField(blank=True, max_length=320, null=True, verbose_name='meta title')),
                ('meta_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='meta description')),
                ('cover_video', models.ImageField(upload_to='about/cover_video/2023/4', verbose_name='Cover Video')),
                ('video', models.FileField(upload_to='about/video/2023/4', verbose_name='Video')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AlterModelOptions(
            name='teammembers',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
