# Generated by Django 4.1.5 on 2023-04-01 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0011_about_alter_teammembers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
