# Generated by Django 4.1.5 on 2023-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0013_about_is_active_en_about_is_active_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='status_fa',
        ),
    ]
