# Generated by Django 4.1.5 on 2023-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0014_remove_socialmedia_status_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cover_video',
            field=models.ImageField(blank=True, null=True, upload_to='about/cover_video/2023/4', verbose_name='Cover Video'),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='about/video/2023/4', verbose_name='Video'),
        ),
    ]
