# Generated by Django 4.1.5 on 2023-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0015_alter_about_cover_video_alter_about_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='landingsections',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='landingsections',
            name='updated_at_jalali',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='created_at_jalali',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='updated_at_jalali',
        ),
    ]
