# Generated by Django 4.1.5 on 2023-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0018_alter_about_cover_video_alter_about_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsections',
            name='cover_background',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_background/2023/5', verbose_name='Cover Background'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_main',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_main/2023/5', verbose_name='Cover Main'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_video',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_video/2023/5', verbose_name='Cover Video'),
        ),
    ]
