# Generated by Django 4.1.5 on 2023-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastres', '0019_alter_landingsections_cover_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cover_video',
            field=models.ImageField(blank=True, null=True, upload_to='about/cover_video/2023/7', verbose_name='Cover Video'),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='about/video/2023/7', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/logo/2023/7', verbose_name='Customer Logo'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_background',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_background/2023/7', verbose_name='Cover Background'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_main',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_main/2023/7', verbose_name='Cover Main'),
        ),
        migrations.AlterField(
            model_name='landingsections',
            name='cover_video',
            field=models.ImageField(blank=True, null=True, upload_to='landing_sections/cover_video/2023/7', verbose_name='Cover Video'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='dastres/about/avatar/2023/7', verbose_name='avatar'),
        ),
    ]
